@echo off
:start
echo MAKE SURE TO RUN THIS AS ADMINISTRATOR OR IT WILL NOT WORK!
echo User Spammer v1.2 (Added Choose)
echo Spams The Users You Want to Spam* Every Time This is Open. you can use this in a real machine.
echo Welcome to CHOOSE.
echo.
echo.
echo THIS MAY MAKE USERS INVISIBLE IN SOME WINDOWS OSes!
echo 1. Spam 25 Users
echo 2. Spam 100 Users
echo 3. exit for safety.
echo I(-)I
set /p choose:={1;2;3;4;5}:
if %choose:%==1 goto 25
if %choose:%==2 goto Payload
if %choose:%==3 goto exit

:exit
echo thank you for exiting for your safety.
echo i mean, thank you for using.
exit

:25
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 

:Payload
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 

net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 

echo DONE!
echo DONE!
echo Testing antivirus...
exit
