@echo off
echo MAKE SURE TO RUN THIS AS ADMINISTRATOR OR IT WILL NOT WORK!
echo User Spammer v1.1 (Super Spam Update, Now Spams 100 Users. it used to spam 25.)
echo Spams 100* Users Every Time This is Open. you can use this in a real machine.
pause
admin
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 

net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 
net user user%random% /add 

echo DONE!
echo DONE!
echo Testing antivirus...
exit
